from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Request
from fastapi.responses import HTMLResponse, PlainTextResponse, Response
from fastapi.templating import Jinja2Templates
from sqlalchemy.orm import Session

from app import dependencies
from app.config import Settings
from app.models import Category, Page, PageStatus
from app.seo import metadata
from app.seo.robots import robots_txt
from app.services.publisher import latest_sitemap
from app.utils.security import check_rate_limit

TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates"
templates = Jinja2Templates(directory=str(TEMPLATE_DIR))

router = APIRouter()
STATIC_PAGES = {
    "about": {
        "title": "About Auto-Posting Money Pages",
        "body": "<p>We publish practical explainers, templates, and bios generated by our AI assisted editorial workflow.</p>",
    },
    "contact": {
        "title": "Contact",
        "body": "<p>Email admin@example.com for partnerships or support.</p>",
    },
    "privacy": {
        "title": "Privacy Policy",
        "body": "<p>We respect reader privacy and only use analytics for aggregate insights.</p>",
    },
    "terms": {
        "title": "Terms",
        "body": "<p>Use this site for inspiration. Content is provided as-is without warranties.</p>",
    },
}


@router.get("/", response_class=HTMLResponse)
def homepage(
    request: Request,
    db: Session = Depends(dependencies.get_db_dep),
    settings: Settings = Depends(dependencies.get_runtime_settings),
):
    latest_pages = (
        db.query(Page)
        .filter(Page.status == PageStatus.PUBLISHED)
        .order_by(Page.published_at.desc())
        .limit(8)
        .all()
    )
    featured = (
        db.query(Page)
        .filter(Page.featured.is_(True))
        .order_by(Page.updated_at.desc())
        .limit(4)
        .all()
    )
    categories = db.query(Category).all()
    context = {
        "request": request,
        "pages": latest_pages,
        "featured": featured or latest_pages[:3],
        "categories": categories,
        "meta": metadata.default_meta(),
        "settings": settings,
    }
    return templates.TemplateResponse("public/home.html", context)


@router.get("/category/{slug}", response_class=HTMLResponse)
def category_page(
    slug: str,
    request: Request,
    db: Session = Depends(dependencies.get_db_dep),
    settings: Settings = Depends(dependencies.get_runtime_settings),
):
    category = db.query(Category).filter(Category.slug == slug).first()
    if not category:
        raise HTTPException(status_code=404)
    pages = (
        db.query(Page)
        .filter(Page.category_id == category.id, Page.status == PageStatus.PUBLISHED)
        .order_by(Page.published_at.desc())
        .all()
    )
    return templates.TemplateResponse(
        "public/category.html",
        {
            "request": request,
            "category": category,
            "pages": pages,
            "meta": metadata.default_meta(),
            "settings": settings,
        },
    )


@router.get("/search", response_class=HTMLResponse)
def search(
    request: Request,
    q: str = Query(""),
    db: Session = Depends(dependencies.get_db_dep),
    settings: Settings = Depends(dependencies.get_runtime_settings),
):
    if q:
        client_host = request.client.host if request.client else "anonymous"
        allowed = check_rate_limit(
            identifier=f"search:{client_host}",
            limit=settings.search_rate_limit_per_minute,
        )
        if not allowed:
            raise HTTPException(status_code=429, detail="Too many search requests")
    query = db.query(Page).filter(Page.status == PageStatus.PUBLISHED)
    if q:
        query = query.filter(Page.title.ilike(f"%{q}%"))
    results = query.order_by(Page.published_at.desc()).limit(20).all()
    return templates.TemplateResponse(
        "public/search.html",
        {
            "request": request,
            "query": q,
            "results": results,
            "meta": metadata.default_meta(),
            "settings": settings,
        },
    )


@router.get("/robots.txt", response_class=PlainTextResponse)
def robots():
    return robots_txt()


@router.get("/sitemap.xml")
def sitemap(db: Session = Depends(dependencies.get_db_dep)):
    xml = latest_sitemap()
    if not xml:
        from app.seo.sitemap import build_sitemap

        xml = build_sitemap(db)
    return Response(content=xml, media_type="application/xml")


@router.get("/rss.xml")
def rss_feed(
    db: Session = Depends(dependencies.get_db_dep),
    settings: Settings = Depends(dependencies.get_runtime_settings),
):
    items = (
        db.query(Page)
        .filter(Page.status == PageStatus.PUBLISHED)
        .order_by(Page.published_at.desc())
        .limit(15)
        .all()
    )
    rss_items = ""
    for page in items:
        link = f"{settings.site_url}/{page.slug}"
        pub_date = page.published_at.isoformat() if page.published_at else ""
        rss_items += f"<item><title>{page.title}</title><link>{link}</link><pubDate>{pub_date}</pubDate></item>"
    xml = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
        "<rss version=\"2.0\"><channel><title>Auto Publishing Feed</title>"
        f"{rss_items}</channel></rss>"
    )
    return Response(content=xml, media_type="application/xml")


def _render_static(slug: str, request: Request, settings: Settings):
    payload = STATIC_PAGES[slug]
    return templates.TemplateResponse(
        "public/static_page.html",
        {"request": request, "title": payload["title"], "body": payload["body"], "settings": settings, "meta": metadata.default_meta()},
    )


@router.get("/about", response_class=HTMLResponse)
def about_page(request: Request, settings: Settings = Depends(dependencies.get_runtime_settings)):
    return _render_static("about", request, settings)


@router.get("/contact", response_class=HTMLResponse)
def contact_page(request: Request, settings: Settings = Depends(dependencies.get_runtime_settings)):
    return _render_static("contact", request, settings)


@router.get("/privacy", response_class=HTMLResponse)
def privacy_page(request: Request, settings: Settings = Depends(dependencies.get_runtime_settings)):
    return _render_static("privacy", request, settings)


@router.get("/terms", response_class=HTMLResponse)
def terms_page(request: Request, settings: Settings = Depends(dependencies.get_runtime_settings)):
    return _render_static("terms", request, settings)


@router.get("/{slug}", response_class=HTMLResponse)
def page_detail(
    slug: str,
    request: Request,
    db: Session = Depends(dependencies.get_db_dep),
    settings: Settings = Depends(dependencies.get_runtime_settings),
):
    page = db.query(Page).filter(Page.slug == slug, Page.status == PageStatus.PUBLISHED).first()
    if not page:
        raise HTTPException(status_code=404)
    related = (
        db.query(Page)
        .filter(Page.id != page.id, Page.category_id == page.category_id, Page.status == PageStatus.PUBLISHED)
        .order_by(Page.published_at.desc())
        .limit(6)
        .all()
    )
    return templates.TemplateResponse(
        "public/page_detail.html",
        {
            "request": request,
            "page": page,
            "related": related,
            "meta": metadata.page_meta(page),
            "settings": settings,
        },
    )


@router.get("/healthz")
def healthcheck():
    return {"status": "ok", "ts": str(
        __import__("datetime").datetime.utcnow()
    )}
